-- Product Keys and License Keys System
-- Run this after the main database creation

-- Product Keys table - generated automatically on registration
CREATE TABLE IF NOT EXISTS product_keys (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_key VARCHAR(100) UNIQUE NOT NULL,
    device_id VARCHAR(255),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    quizzes_taken INT DEFAULT 0,
    quiz_limit INT DEFAULT 5, -- Free tier limit
    activation_status ENUM('trial', 'activated', 'expired') DEFAULT 'trial',
    activated_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- License Keys table - generated by admin for Product Keys
CREATE TABLE IF NOT EXISTS license_keys (
    id INT AUTO_INCREMENT PRIMARY KEY,
    license_key VARCHAR(100) UNIQUE NOT NULL,
    product_key VARCHAR(100) NOT NULL,
    generated_by INT NOT NULL, -- Admin who generated it
    expiry_date TIMESTAMP NULL,
    max_activations INT DEFAULT 1,
    current_activations INT DEFAULT 0,
    status ENUM('active', 'used', 'expired', 'revoked') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activated_at TIMESTAMP NULL,
    FOREIGN KEY (product_key) REFERENCES product_keys(product_key) ON DELETE CASCADE,
    FOREIGN KEY (generated_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Add activation tracking to users table
ALTER TABLE users ADD COLUMN product_key VARCHAR(100) UNIQUE;
ALTER TABLE users ADD COLUMN account_type ENUM('trial', 'premium') DEFAULT 'trial';
ALTER TABLE users ADD COLUMN activation_date TIMESTAMP NULL;

-- Update existing users to have trial accounts
UPDATE users SET account_type = 'trial' WHERE account_type IS NULL;
